### ISSUE TITLE
infografia 

### ISSUE THREAD

**Issue by evelyn-santiago** [SistemasTecTlaxiaco/actividad-1-infografia-evelyn-santiago#1]
[Infografía Ciclo de Vida del Desarrollo de Software SDLC.pdf](https://github.com/user-attachments/files/16811300/Infografia.Ciclo.de.Vida.del.Desarrollo.de.Software.SDLC.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días compañera, excelente trabajo.
Porcentaje obtenido en base a la rúbrica: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
